### ISSUE TITLE
ValueError:

### ISSUE THREAD

**Issue by Xiuxiu21** [Cocofeat/TBraTS#4]
Epoch 1/198
Traceback (most recent call last):
  File "G:/ TBraTS-main/TBraTS-main/trainTBraTS.py", line 268, in <module>
    epoch_loss = train(epoch)
  File "G:/ TBraTS-main/TBraTS-main/trainTBraTS.py", line 127, in train
    evidences, evidence_a, loss = model(x,target,epoch,args.mode)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by Cocofeat** [comment]
Thanks for your attention!
line 268 is ok.
line 127 is modified

**Comment by Xiuxiu21** [comment]
> Thanks for your attention! line 268 is ok. line 127 is modified

<img width="628" alt="image" src="https://user-images.githubusercontent.com/101190274/192416503-7736e5c1-fb5c-4dc4-a836-a3fdd291aebe.png">
这里是否也需要修改呢

**Comment by Cocofeat** [comment]
Yeah, right!



在 2022-09-27 10:22:25，"Xiuxiu21" ***@***.***> 写道：

Thanks for your attention! line 268 is ok. line 127 is modified

这里是否也需要修改呢

**Comment by Xiuxiu21** [comment]
> Yeah, right! 在 2022-09-27 10:22:25，"Xiuxiu21" ***@***.***> 写道： Thanks for your attention! line 268 is ok. line 127 is modified 这里是否也需要修改呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

![image](https://user-images.githubusercontent.com/101190274/192417772-5df01f0d-0764-4edd-8658-c0e7dd764ff4.png)
请问我该如何修改这部分让3正确运行呢?

**Comment by Cocofeat** [comment]
you should check the input data, detail about the Lines 213-248 "sample = transform(sample)"
