### ISSUE TITLE
predict

### ISSUE THREAD

**Issue by Xiuxiu21** [Cocofeat/TBraTS#5]
Thank you for your work！
Traceback (most recent call last):
  File "G:/ TBraTS-main/TBraTS-main/trainTBraTS.py", line 277, in <module>
    val_loss, best_dice = val(args, epoch, best_dice)
  File "G:/ TBraTS-main/TBraTS-main/trainTBraTS.py", line 161, in val
    args.mode)  # two modality or four modality
  File "C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\ TBraTS-main\TBraTS-main\models\trustedseg.py", line 55, in forward
    backbone_output = tailor_and_concat(X, self.backbone)
  File "G:\ TBraTS-main\TBraTS-main\predict.py", line 90, in tailor_and_concat
    temp.append(x[..., :128, :128, :128])
TypeError: unhashable type: 'slice'

进程已结束，退出代码 1

**Comment by Cocofeat** [comment]
Whether your data has been preprocessed, please refer to the code for preprocessing
“Follow the python3 data/preprocessBraTS.py which is referenced from the [TransBTS](https://github.com/Wenxuan-1119/TransBTS/blob/main/data/preprocess.py)”

**Comment by Xiuxiu21** [comment]
> 

我已按照您的方法处理数据，但还是有这个问题

**Comment by Cocofeat** [comment]
You should carefully check your input data.
More details could you provide?



在 2022-09-26 21:46:10，"Xiuxiu21" ***@***.***> 写道：

我已按照您的方法处理数据，但还是有这个问题

**Comment by Xiuxiu21** [comment]
您好，我又将数据按照transbts进行处理，为了方便测试将训练数据改为一个病例，仍然出现一下情况

![1664240536814](https://user-images.githubusercontent.com/101190274/192407412-bf9ebc23-290b-41bd-88db-b3ea293c5795.jpg)
如果方便的话您可以即将您处理好的数据发给我吗，十分感谢！！！这是我的邮箱：3190221518@qq.com

**Comment by Cocofeat** [comment]
There is a high probability that there is a problem with the definition of “temp”, please check it carefully.
The data is relatively large, 
if others have this problem, I will upload it to the cloud disk when I am free

**Comment by Xiuxiu21** [comment]
我怕该如何解决此问题






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cocofeat/TBraTS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月27日(星期二) 上午9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Cocofeat/TBraTS] predict (Issue #5)





 
There is a high probability that there is a problem with the definition of “temp”, please check it carefully.
 The data is relatively large,
 if others have this problem, I will upload it to the cloud disk when I am free

**Comment by Cocofeat** [comment]
you should check the input data, detail about the Lines 213-248 "sample = transform(sample)"

**Comment by Xiuxiu21** [comment]
> you should check the input data, detail about the Lines 213-248 "sample = transform(sample)我解决了这个问题，请问这部分是否有问题呢
<img width="797" alt="image" src="https://user-images.githubusercontent.com/101190274/192663867-5afe0b7c-030e-451e-8b80-2274049a7287.png">
<img width="778" alt="image" src="https://user-images.githubusercontent.com/101190274/192663882-13608c10-3c46-470b-9b19-9031f963ca92.png">

**Comment by noteless517** [comment]
I met the same problem in the validation but I found that it's because in the trainTBraTS.py,  the x is created as a dictionary, it can't be used with the code temp.append(x[..., :128, :128, :128]). Would you like to renew your code to help us? 
![20230424215135](https://user-images.githubusercontent.com/80697777/234017428-9b45c0ff-806e-46c9-b459-ce07cb9fc4eb.png)

**Comment by Cocofeat** [comment]
Sorry to make you confused. We have check the codes on the journal version. please check in follow link.
https://github.com/Cocofeat/UMIS/blob/31fef3f679c9c4dc5def1c4ec1e204a22e446b52/trainUMIS.py#L283

Note: 
This is because we only used 2 modal inputs in the early version, and 4 modal inputs in the later version, and the BraTS dataset can be trained directly based on the above connection. The process of training BraTS can also refer to TransBTS.
https://github.com/Wenxuan-1119/TransBTS

**Comment by noteless517** [comment]
> 

Thanks a lot. That's really helpful.

**Comment by Lemonweier** [comment]
Hello, we use brats2019 data set, our data set does not have validation labels, do you have any? Is uploaded where to view model accuracy, thanks for reply!
